"""added new columns

Revision ID: 9a7a3c237242
Revises: d3b4a96117dd
Create Date: 2026-02-13 16:22:37.813082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a7a3c237242'
down_revision: Union[str, Sequence[str], None] = 'd3b4a96117dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('processing_status', sa.String(), server_default='not processed', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_status')
    # ### end Alembic commands ###
