"""added new columns

Revision ID: cb15fb484c5a
Revises: 9a7a3c237242
Create Date: 2026-02-14 12:13:19.365040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb15fb484c5a'
down_revision: Union[str, Sequence[str], None] = '9a7a3c237242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'content_type')
    # ### end Alembic commands ###
