"""add new columns in document table

Revision ID: d3b4a96117dd
Revises: 43a78e455bac
Create Date: 2026-02-11 11:24:42.045889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3b4a96117dd'
down_revision: Union[str, Sequence[str], None] = '43a78e455bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('upload_time', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_documents_file_id'), 'documents', ['file_id'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_id'), table_name='documents')
    op.drop_column('documents', 'upload_time')
    # ### end Alembic commands ###
